name: Model Retraining on Push to Main

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate and Store Timestamp
      run: |
        timestamp=$(date '+%Y%m%d%H%M%S')
        echo "$timestamp" > timestamp.txt
      id: timestamp 

    - name: Check File Permissions
      run: |
        ls -l ./src/train_model.py

    - name: Set File Permissions
      run: |
        chmod +x ./src/train_model.py #making it executable

    - name: Ensure Directories Exist
      run: |
        mkdir -p Labs/Github_Labs/Lab2/metrics
        mkdir -p Labs/Github_Labs/Lab2/models
        mkdir -p Labs/Github_Labs/Lab2/data

    - name: Retrain Model
      run: |
        timestamp=$(cat timestamp.txt) # Use the timestamp in your training script
        python ./src/train_model.py --timestamp "$timestamp"

    - name: Evaluate Model and Log Metrics
      run: |
        timestamp=$(cat timestamp.txt)
        # Change into the correct directory for the script to run properly
        cd Labs/Github_Labs/Lab2/src
        python evaluate_model.py --timestamp "$timestamp"
        
        # Move the file from the src directory to the metrics directory
        metrics_filename="${timestamp}_metrics.json"
        mkdir -p ../metrics # Ensure the metrics directory exists
        if [ -f "$metrics_filename" ]; then
          mv "$metrics_filename" ../metrics/
        fi
      continue-on-error: false

    - name: Store and Version the New Model
      run: |
        timestamp=$(cat timestamp.txt)
        model_filename="model_${timestamp}_dt_model.joblib"
        mkdir -p Labs/Github_Labs/Lab2/models
        if [ -f "$model_filename" ]; then
          mv "$model_filename" Labs/Github_Labs/Lab2/models/
        fi

    - name: Commit and Push Changes
      run: |
        timestamp=$(cat timestamp.txt)
        metrics_filename="${timestamp}_metrics.json"
        model_filename="model_${timestamp}_dt_model.joblib"
        git config --global user.email "26876927+raminmohammadi@users.noreply.github.com"
        git config --global user.name "raminmohammadi"
        git add metrics/$metrics_filename models/$model_filename
        git commit -m "Add metrics and updated model [timestamp: $timestamp]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
