name: Periodic Model Calibration

on: 
  schedule:
    - cron: '0 0 * * *'  #minutes, hours, day, month, day of week 

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate and Store Timestamp
      run: |
        timestamp=$(date '+%Y%m%d%H%M%S')
        echo "$timestamp" > timestamp.txt
      id: timestamp 

    - name: Check File Permissions
      run: |
        ls -l ./src/train_model.py

    - name: Set File Permissions
      run: |
        chmod +x ./src/train_model.py

    - name: Ensure Directories Exist
      run: |
        mkdir -p Labs/Github_Labs/Lab2/metrics
        mkdir -p Labs/Github_Labs/Lab2/models
        mkdir -p Labs/Github_Labs/Lab2/data

    - name: Retrain Model
      run: |
        timestamp=$(cat timestamp.txt) # Use the timestamp in your training script
        python ./src/train_model.py --timestamp "$timestamp"

    - name: Evaluate Model and Log Metrics
      run: |
        timestamp=$(cat timestamp.txt)
        python Labs/Github_Labs/Lab2/src/evaluate_model.py --timestamp "$timestamp"
      continue-on-error: false

    - name: Store and Version the New Model
      run: |
        timestamp=$(cat timestamp.txt)
        python Labs/Github_Labs/Lab2/src/train_model.py --timestamp "$timestamp"

    - name: Commit and Push Changes
      run: |
        timestamp=$(cat timestamp.txt)
        metrics_filename="${timestamp}_metrics.json"
        model_filename="model_${timestamp}_dt_model.joblib"
        git config --global user.email "26876927+raminmohammadi@users.noreply.github.com"
        git config --global user.name "raminmohammadi"

        git add Labs/Github_Labs/Lab2/metrics/"$metrics_filename" Labs/Github_Labs/Lab2/models/"$model_filename"
        
        git commit -m "Add metrics and updated model [timestamp: $timestamp]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



